apiVersion: ENC[AES256_GCM,data:wLc=,iv:IWvcteSrBLjPbjuAUWmqgcU+KWh9sxJ4w42Mfp/9W9E=,tag:rJyvm4ci7vwRr0eSoCyl9A==,type:str]
kind: ENC[AES256_GCM,data:pNgb+9fr,iv:e6KgAGvOEZoia7M4EYHKxgmntqbVUKauoRXprEXUxco=,tag:erDg17tPnDQsLYYYaU8thA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nSpDglohIT48doqnGhFe9zI=,iv:CJhMjVDZUQTxrPZqlCBvB7PQLI5SekLlu6Uh2o3VOWU=,tag:gx9KZFqscvNuijebQdfmTg==,type:str]
    namespace: ENC[AES256_GCM,data:cTMLLZEoebvk,iv:R0R3hcOJu7Hgm3Zw1YMgC9yx7HjEqQxQvPnz07A+N4A=,tag:NqCpevXQd/omDw0lPaNcBA==,type:str]
stringData:
    RESEND_API_KEY: ENC[AES256_GCM,data:dkCiRtXrob9f1vXTTaFmtKRY+J2u8OotkH4vBynorg2YdOGu,iv:mx0LGLy30StjfvJM7K6pqYV4QQChH+Cfj53NnzV2jBI=,tag:aMjiKrzGPcRcJM7OnQsG3A==,type:str]
sops:
    age:
        - recipient: age14mycsk7clgt7z7g99eh3hqq90pjlk77s37udzkh68ksrekaum4yqznl4z2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWkJ1cnptUFpzTXBkZzN3
            NWZOTzNrQlJDN2JDOEI3L0R0Q01VUE1XdHlRCkl0Z1Z6Sml2eGJpbWJ4KzJjV1Ex
            UmZtVE5Nd1ppQkVDcEhUK2NLbVZteWMKLS0tIDBrODRrWUdXTWd2RzBmLytLb1I5
            d0pCZ01PaWpySGJaN1gvY1d0TUNla0kK3OnvGjZhuY2xmtKWnhXkln4l+DnlavFb
            nlQdJdc/oXoi5Lk1EUbctgCNaXnXEln6Cjj9EAc2EKQOiAtHJBEvbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T22:34:20Z"
    mac: ENC[AES256_GCM,data:E5bw0gKUrU6UIkIYd+G2neg+ftSZGqozGLbaZGL7BlcEvnwW7aqtOZTaFeRl4hKC28B6Kixkwa3/OcFgrfizPAlvfM0o0QuQewEEPy2bgCnOYfKvadj9AplrcFpAhpt8vPJ0vRaZykWfonM2T9F8O+RV8sTEoQCORN1eSGeafoc=,iv:IfZx+mmBm10YGrsPWKPSUPDswGJflbTwKtD0kF4Ukqc=,tag:bQYDloK51mfthPxp2HRUog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
