apiVersion: ENC[AES256_GCM,data:CQg=,iv:+1m40397wX11jqf/9dLoERoXKGrXjWnmv8MDAIUsh9Q=,tag:TN7bDzE4L6vC3qFfoNcR7A==,type:str]
kind: ENC[AES256_GCM,data:fxHK0qSa,iv:8e6VfvH0R25d35omAFsKe15uUafaRf3pG/wzm90G+tQ=,tag:FsuO/dXKHznZpvZtn1pKCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t6PTN+sywWHQVzXybnc8LAw=,iv:6fWMMv06UdZ9sgtLc3haw/deXL31AJAdnbOlLlAKv+A=,tag:ONW6AfIi0qxG2oSiuWpu1Q==,type:str]
    namespace: ENC[AES256_GCM,data:ceTdeNioPsfq,iv:8FvOetjhHfi51CqF8LSBBGe6UNBNcno+DQUjHd1iKO4=,tag:EiNCUZkW5LQcNESHi7Ek/A==,type:str]
stringData:
    RESEND_API_KEY: ENC[AES256_GCM,data:kBy+iYhwWdvhPATaIi8AIxSVsF0s9HGz0E66,iv:UQxLELzKi2zvcc4rL22A2cLIUsAcrtA1RcnJAdtVX98=,tag:GABuVvZUJSioTsOwsVIWpw==,type:str]
sops:
    age:
        - recipient: age14mycsk7clgt7z7g99eh3hqq90pjlk77s37udzkh68ksrekaum4yqznl4z2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTndrV0Vsbk5qTVVxbzhi
            bWY5MjhLYnFFQ05GUC8yY3dmM3doNDZFWTBRCkJVUm40aXdxd00vQUxvUVBwdGRV
            NDZzUUgyVnZ6UlluSXoxU0x3RUFzUGsKLS0tIEpJSVBoZUNGSkVtWU1vbU5yQ3FL
            dFp5R2JPQktIVGxkWUN0Uzd4MkZPaWsKhdrQBWK2SHzvsIjtKHZTedwMFSSLyVxm
            Esk1Pxy350cmsoeZ60aGMCFLQCHbarhy1Kh1yzTShtAtmihRj9NuXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T22:14:38Z"
    mac: ENC[AES256_GCM,data:rM+v7c5+7wwdGnJrj0YjTUGQmUJFtnHyHKq1d0MnRjD27UAdO+2cCjXtwv2Yd2nGywsqrdvh9orCTzj4lEfSfoKt20fLrjBf1Jw+6+tnqMjnIHAsK2UU1EjlzGRJK7qVMU6eCE8lxuHEY1Q4LJNvNshsjEOedZ8kvP/T8SLXiG0=,iv:EvOQSp+0A798piDa6cxOwdwLWkOIKYBZVHdqujKkKHA=,tag:LYwwaXaiUGhYKkrhgkS8QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
